### ISSUE TITLE
Feedback Daniel

### ISSUE THREAD

**Issue by palcu** [infoeducatie/infoeducatie-ui#90]
## TODO
- [x] steluta la campurile obligatorii
- [x] tara default romania (in getInitialState)
- [x] orasul si judetul si tara scolii sa se treaca automat (scoti mixinul de pe fieldurile astea si pui event de onChange de mana)
- [x] validare CNP
- [x] cand intri pe pagina de participanti, la componentDidMount, fă refresh la current
- [x] s/`reseteaza`/`toate categoriile` pe pagina de participanti
- [x] toate categoriile trece la inceput, si cand sunt toate selectate, apare doar cerculet in jurul lui toate
- [x] clickable tot randul la participanti sa duca la forum
- [x] clickable tot cardul la participanti sa duca la forum
- [x] scoate cu totul norisorul de la participanti
- [x] titlurile de tabel aliniate la stanga
- [x] muta rezultatele jos si seminarii sus in meniu
- [x] pe contact nu se vad iconitele
- [x] scoate poza Luiza
- [x] scoate inregistrare din footer
- [x] criteriile de jurizare sa fie si la despre
- [x] stirile de pe prima pagina sa aiba logica
- [x] judetele sa fie alese dintr-o lista
- [x] la surse cu adresa sursei si documentatiei scrie un mesaj mai mare (pui un p mare cu warning explicatii)
- [x] nu mai poti sa dai bani si sa te inscrii la register
- [x] la criterii si rezultate sa fie PDF
## TODO daca mai avem timp
- [x] validare la adresa sursei
- [x] orasele intr-o lista

**Comment by robertdxyz** [comment]
Toate care nu au fost rezolvate au issue separat
